project_id = "pkiajhllkihkuchbwrgz"

[functions.blog-writer]
verify_jwt = true

[functions.generate-financial-report]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.send-invoice-reminder]
verify_jwt = true

[functions.suggest-service-details]
verify_jwt = false

[functions.bms-intent-parser]
verify_jwt = false

[functions.bms-api-bridge]
verify_jwt = false

[functions.whatsapp-bms-handler]
verify_jwt = false

[functions.generate-whatsapp-document]
verify_jwt = false
